### ISSUE TITLE
[Risk] Depth of vendor pool for agile delivery and modular procurements

### ISSUE THREAD

**Issue by edmullen** [18F/acq-alaska-dhss-modernization#35]
[Example of using issues to track risks] 

## The depth of the vendor pool available that understands agile delivery and can do modular procurement might be limited.

This could particularly be problematic in the early phases of the project.

We continue to investigate the existence of these vendors. As we evaluate this risk, we will update this issue.

**Comment by edmullen** [comment]
A [vendor information section](https://github.com/18F/acq-alaska-dhss-modernization/blob/master/vendor-info/README.md) has been created to communicate to the vendor community and a [Request for Information](https://github.com/18F/acq-alaska-dhss-modernization/blob/master/vendor-info/README.md#so-whats-next) has been posted to begin to assess vendor interest.

**Comment by mheadd** [comment]
Closing this issue, as we evaluate other tools to track project risks.
