### ISSUE TITLE
Public technical prototype resources

### ISSUE THREAD

**Issue by ralreegorganon** [18F/acq-alaska-dhss-modernization#37]
What is the the plan/timeline for making some of the currently private technical resources for the prototype public? I was hoping to take a look at the repository (the link to which I see was actually just removed in #36) as well as the Trello board, but I see those are private for the moment. 

Is the current prototype also fulfilling the role of the MVP defined in the [dev ops document](https://github.com/18F/acq-alaska-dhss-modernization/blob/master/DevOps.md), or is that a separate effort? Any plans for further public discussion of the approach, architecture and technology stack outlined there?

**Comment by randyhart** [comment]
@ralreegorganon - FYI we are working on a response to this along with other questions/feedback from vendors that were sent in response to Alaska's RFI.  We will post more information in the coming days.  Thank you for your interest!

**Comment by ralreegorganon** [comment]
@randyhart - great, looking forward to seeing it. I'll go ahead and close this, as it sounds like you'll be delivering the response to this question as part of a larger effort.
